{
  config,
  lib,
  home,
  pkgs,
  ...
}: {
  home.file."Library/Application Support/nushell/config.nu".text = ''
$env.config.buffer_editor = 'code';
$env.PATH = $env.PATH ++ [
  "/run/current-system/sw/bin",
  "/nix/var/nix/profiles/default/bin",
  "/Users/wint3rmute/.nix-profile/bin",
  "/etc/profiles/per-user/wint3rmute/bin",
];

# Helper functions to get branch names
def git_main_branch [] {
    let branches = (git branch -r | lines | str trim)
    if ($branches | any {|b| $b =~ "origin/main"}) {
        "main"
    } else if ($branches | any {|b| $b =~ "origin/master"}) {
        "master"
    } else {
        "main"
    }
}

def git_develop_branch [] {
    let branches = (git branch -r | lines | str trim)
    if ($branches | any {|b| $b =~ "origin/develop"}) {
        "develop"
    } else {
        "dev"
    }
}

def git_current_branch [] {
    git rev-parse --abbrev-ref HEAD
}

# Basic commands
alias g = git
alias ga = git add
alias gaa = git add --all
alias gapa = git add --patch
alias gau = git add --update
alias gco = git checkout
alias gcb = git checkout -b
alias gcm = git checkout (git_main_branch)
alias gcd = git checkout (git_develop_branch)

# Commit commands
alias gc = git commit --verbose
alias gca = git commit --verbose --all
alias gcam = git commit --all --message
alias gcmsg = git commit --message
alias "gc!" = git commit --verbose --amend
alias "gcan!" = git commit --verbose --all --no-edit --amend
alias gcf = git commit --fixup

# Branch commands
alias gb = git branch
alias gba = git branch --all
alias gbd = git branch --delete
alias gbD = git branch --delete --force
alias gbm = git branch --move
alias ggsup = git branch --set-upstream-to=origin/(git_current_branch)

# Switch commands
alias gsw = git switch
alias gswc = git switch -c

# Push & Pull commands
alias gl = git pull
alias gp = git push
alias gpr = git pull --rebase
alias gpra = git pull --rebase --autostash
alias gpf = git push --force-with-lease
alias gpsup = git push --set-upstream origin (git_current_branch)
alias ggp = git push origin (git_current_branch)
alias ggl = git pull origin (git_current_branch)

# Log & Diff commands
alias glog = git log --oneline --decorate --graph
alias gloga = git log --oneline --decorate --graph --all
alias glol = git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'
alias gd = git diff
alias gdca = git diff --cached
alias gdw = git diff --word-diff

# Status & Stash commands
alias gst = git status
alias gss = git status --short
alias gsta = git stash push
alias gsts = git stash show --patch

# Merge & Rebase commands
alias gm = git merge
alias gma = git merge --abort
alias gms = git merge --squash
alias gmff = git merge --ff-only

# Other useful shortcuts
alias gf = git fetch
alias gfa = git fetch --all --tags --prune
alias gcp = git cherry-pick
alias grt = cd (git rev-parse --show-toplevel)
alias gwip = git add -A; git commit -m "WIP"

source ~/.config/zoxide.nu
  '';

  home.file.".config/zoxide.nu".text = ''
# Code generated by zoxide. DO NOT EDIT.

# =============================================================================
#
# Hook configuration for zoxide.
#

# Initialize hook to add new entries to the database.
export-env {
  $env.config = (
    $env.config?
    | default {}
    | upsert hooks { default {} }
    | upsert hooks.env_change { default {} }
    | upsert hooks.env_change.PWD { default [] }
  )
  let __zoxide_hooked = (
    $env.config.hooks.env_change.PWD | any { try { get __zoxide_hook } catch { false } }
  )
  if not $__zoxide_hooked {
    $env.config.hooks.env_change.PWD = ($env.config.hooks.env_change.PWD | append {
      __zoxide_hook: true,
      code: {|_, dir| zoxide add -- $dir}
    })
  }
}

# =============================================================================
#
# When using zoxide with --no-cmd, alias these internal functions as desired.
#

# Jump to a directory using only keywords.
def --env --wrapped __zoxide_z [...rest: string] {
  let path = match $rest {
    [] => {'~'},
    [ '-' ] => {'-'},
    [ $arg ] if ($arg | path expand | path type) == 'dir' => {$arg}
    _ => {
      zoxide query --exclude $env.PWD -- ...$rest | str trim -r -c "\n"
    }
  }
  cd $path
}

# Jump to a directory using interactive search.
def --env --wrapped __zoxide_zi [...rest:string] {
  cd $'(zoxide query --interactive -- ...$rest | str trim -r -c "\n")'
}

# =============================================================================
#
# Commands for zoxide. Disable these using --no-cmd.
#

alias cd = __zoxide_z
alias zi = __zoxide_zi

# =============================================================================
#
# Add this to your env file (find it by running `$nu.env-path` in Nushell):
#
#   zoxide init nushell | save -f ~/.zoxide.nu
#
# Now, add this to the end of your config file (find it by running
# `$nu.config-path` in Nushell):
#
#   source ~/.zoxide.nu
#
# Note: zoxide only supports Nushell v0.89.0+.
  '';
}
