{
  description = "Wint3rmute's Flake Configuration";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin.url = "github:nix-darwin/nix-darwin/master";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    agenix = {
      url = "github:ryantm/agenix";
      inputs.darwin.follows = "nixpkgs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = inputs @ {
    self,
    nix-darwin,
    nixpkgs,
    home-manager,
    agenix,
  }: let
    configuration = {
      pkgs,
      home-manager,
      ...
    }: {
      home-manager.users.wint3rmute = {
        imports = [
          ./modules/home_packages.nix
          ./modules/helix.nix
          ./modules/git.nix
          ./modules/nushell.nix
        ];
        home.homeDirectory = "/Users/wint3rmute";
        home.stateVersion = "25.05";

        home.file."Library/Application Support/nushell/config.nu".text = ''
          $env.config.buffer_editor = 'code';
          $env.PATH = $env.PATH ++ [
            "/run/current-system/sw/bin",
            "/nix/var/nix/profiles/default/bin",
            "/Users/wint3rmute/.nix-profile/bin",
            "/etc/profiles/per-user/wint3rmute/bin",
          ];

          source ~/.config/zoxide.nu
        '';

      home.file.".config/zoxide.nu".text = ''
# Code generated by zoxide. DO NOT EDIT.

# =============================================================================
#
# Hook configuration for zoxide.
#

# Initialize hook to add new entries to the database.
export-env {
  $env.config = (
    $env.config?
    | default {}
    | upsert hooks { default {} }
    | upsert hooks.env_change { default {} }
    | upsert hooks.env_change.PWD { default [] }
  )
  let __zoxide_hooked = (
    $env.config.hooks.env_change.PWD | any { try { get __zoxide_hook } catch { false } }
  )
  if not $__zoxide_hooked {
    $env.config.hooks.env_change.PWD = ($env.config.hooks.env_change.PWD | append {
      __zoxide_hook: true,
      code: {|_, dir| zoxide add -- $dir}
    })
  }
}

# =============================================================================
#
# When using zoxide with --no-cmd, alias these internal functions as desired.
#

# Jump to a directory using only keywords.
def --env --wrapped __zoxide_z [...rest: string] {
  let path = match $rest {
    [] => {'~'},
    [ '-' ] => {'-'},
    [ $arg ] if ($arg | path expand | path type) == 'dir' => {$arg}
    _ => {
      zoxide query --exclude $env.PWD -- ...$rest | str trim -r -c "\n"
    }
  }
  cd $path
}

# Jump to a directory using interactive search.
def --env --wrapped __zoxide_zi [...rest:string] {
  cd $'(zoxide query --interactive -- ...$rest | str trim -r -c "\n")'
}

# =============================================================================
#
# Commands for zoxide. Disable these using --no-cmd.
#

alias cd = __zoxide_z
alias zi = __zoxide_zi

# =============================================================================
#
# Add this to your env file (find it by running `$nu.env-path` in Nushell):
#
#   zoxide init nushell | save -f ~/.zoxide.nu
#
# Now, add this to the end of your config file (find it by running
# `$nu.config-path` in Nushell):
#
#   source ~/.zoxide.nu
#
# Note: zoxide only supports Nushell v0.89.0+.
      '';
      
      };

      environment.systemPackages = [agenix.packages.aarch64-darwin.default];

      users.users.wint3rmute = {
        name = "wint3rmute";
        home = "/Users/wint3rmute";
        uid = 501;

        shell = pkgs.nushell;
      };
      system.primaryUser = "wint3rmute";

      # for programs.zsh.enableCompletion. Comment in docs:
      # Enable zsh completion. Don’t forget to add
      environment.pathsToLink = ["/share/zsh"];

      home-manager.useGlobalPkgs = true;
      home-manager.useUserPackages = true;

      # Necessary for using flakes on this system.
      nix.settings.experimental-features = "nix-command flakes";

      # Set Git commit hash for darwin-version.
      system.configurationRevision = self.rev or self.dirtyRev or null;

      # Used for backwards compatibility, please read the changelog before changing.
      # $ darwin-rebuild changelog
      system.stateVersion = 6;

      # The platform the configuration will be used on.
      nixpkgs.hostPlatform = "aarch64-darwin";

      nixpkgs.config.allowUnfree = true;
    };
  in {
    formatter.aarch64-darwin = nixpkgs.legacyPackages.aarch64-darwin.alejandra;
    darwinConfigurations."Mateuszs-MacBook-Air" = nix-darwin.lib.darwinSystem {
      modules = [
        agenix.nixosModules.default
        home-manager.darwinModules.home-manager
        configuration
        ./modules/hosts.nix
        ./modules/global_packages.nix
        ./modules/macos.nix
        ./modules/homebrew.nix
      ];
    };
  };
}
